### ISSUE TITLE
Problem z metodą PUT (x-http-method-override = PATCH)

### ISSUE THREAD

**Issue by arkadiusz-wieczorek** [Sealious/sealious-base-chips#30]
Podczas wysyłania PUTa na zasób o konkretnym id.

``` bash
17:07:33.808 - info: Sealious@0.4.7 is up-to-date.
17:07:51.324 - info: GET /api/v1/places - success!
17:07:52.789 - info: POST /login - success!
17:07:54.690 - info: POST /login - success!
UNIFIED! PATCH
17:08:03.101 - error:  TypeError: Cannot read property 'body' of null
    at /home/arkadiusz/Projects/Sealious-dev/Sealious/lib/core-services/resource-manager.js:163:89
    at tryCatcher (/home/arkadiusz/Projects/Sealious-dev/Sealious/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/home/arkadiusz/Projects/Sealious-dev/Sealious/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/home/arkadiusz/Projects/Sealious-dev/Sealious/node_modules/bluebird/js/main/promise.js:530:18)
    at bound (domain.js:254:14)
    at Promise.runBound (domain.js:267:12)
    at Async._drainQueue (/home/arkadiusz/Projects/Sealious-dev/Sealious/node_modules/bluebird/js/main/async.js:182:12)
    at Async._drainQueues (/home/arkadiusz/Projects/Sealious-dev/Sealious/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/arkadiusz/Projects/Sealious-dev/Sealious/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)
TypeError: Cannot read property 'body' of null
    at /home/arkadiusz/Projects/Sealious-dev/Sealious/lib/core-services/resource-manager.js:163:89
    at tryCatcher (/home/arkadiusz/Projects/Sealious-dev/Sealious/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/home/arkadiusz/Projects/Sealious-dev/Sealious/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/home/arkadiusz/Projects/Sealious-dev/Sealious/node_modules/bluebird/js/main/promise.js:530:18)
    at bound (domain.js:254:14)
    at Promise.runBound (domain.js:267:12)
    at Async._drainQueue (/home/arkadiusz/Projects/Sealious-dev/Sealious/node_modules/bluebird/js/main/async.js:182:12)
    at Async._drainQueues (/home/arkadiusz/Projects/Sealious-dev/Sealious/node_modules/bluebird/js/main/async.js:187:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/arkadiusz/Projects/Sealious-dev/Sealious/node_modules/bluebird/js/main/async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:358:17)


```

**Comment by kuba-orlik** [comment]
Naprawione w 6e7dd77984b060f34d63615d95b447fe8b4db316
