### ISSUE TITLE
Out-of-date color field-type in repository (Merge compatibility_with_0.6)

### ISSUE THREAD

**Issue by arkadiusz-wieczorek** [Sealious/sealious-base-chips#37]
After installation sealious@0.6.3, an error occurs when starting the application becasue `field-type.color` is out-of-date. Is it https://github.com/Sealious/sealious-www-server/tree/compatibility_with_0.6 branch ready to merge?

``` js
arkadiusz@arkadiusz-ThinkPad-X200:~/Projects/Placetag/placetag-app$ sudo node .
18:25:48.775 - info: Detected plugin sealious-www-server
/home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious-www-server/define/field_type.color.js:7
field_type_color.prototype.isProperValue = function(value_in_code){
                                         ^

TypeError: Cannot set property 'isProperValue' of undefined
    at Object.<anonymous> (/home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious-www-server/define/field_type.color.js:7:42)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious-www-server/sealious-www-server.js:5:1)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at load_plugins_from_dir (/home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious/lib/plugins/plugin-manager.js:22:18)
    at load_plugins (/home/arkadiusz/Projects/Placetag/placetag-app/node_modules/sealious/lib/plugins/plugin-manager.js:29:3)
```

**Comment by kuba-orlik** [comment]
I've merged the branch and published the plugin. If you use sealious@next, install www-server with `npm install --save sealious-www-server@next` :)

**Comment by arkadiusz-wieczorek** [comment]
Ok, I will test.

**Comment by arkadiusz-wieczorek** [comment]
Npm doesn't see `sealious-www-server@next`, but `npm install --save sealious-www-server@0.6.1` it works

``` bash
arkadiusz@arkadiusz-ThinkPad-X200:~/Projects/Placetag/placetag-app$ sudo npm install --save sealious-www-server@next
npm WARN package.json placetag-app@0.1.0 No repository field.
npm WARN package.json placetag-app@0.1.0 No README data
npm ERR! Linux 3.13.0-22-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--save" "sealious-www-server@next"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.3
npm ERR! code ETARGET

npm ERR! notarget No compatible version found: sealious-www-server@'next'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.4.3","0.5.0","0.5.1","0.5.2","0.5.3","0.6.0","0.6.1"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'placetag-app'
npm ERR! notarget 

npm ERR! Please include the following file with any support request:
npm ERR!     /home/arkadiusz/Projects/Placetag/placetag-app/npm-debug.log
arkadiusz@arkadiusz-ThinkPad-X200:~/Projects/Placetag/placetag-app$ 
```

**Comment by kuba-orlik** [comment]
Ok then, I've decided to move both Sealious and www-server out of "next" phase, since they seem to behave nicely right now. Installing latest `sealious` and `sealious-www-server` packages (without any distro-@tags) should work now.

**Comment by arkadiusz-wieczorek** [comment]
Ok, it works now.
